database:
  connections:
    world-governance-index:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "WorldGovernanceIndicators"
      username: "admin"
      password: "123"
    doing-bussiness:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "DoingBusiness"
      username: "admin"
      password: "123"
    transformation-index:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "TransformationIndex"
      username: "admin"
      password: "123"
    economic-freedom:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "EconomicFreedom"
      username: "admin"
      password: "123"
