database:
  connections:
    world-governance-index:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "wgi"
      username: "root"
      password: "admin"
    doing-bussiness:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "db"
      username: "root"
      password: "admin"
    transformation-index:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "ti"
      username: "root"
      password: "admin"
    economic-freedom:
      dialect: "mysql"
      driver: "mysqlconnector"
      host: "localhost"
      port: 3306
      schema: "ef"
      username: "root"
      password: "admin"
